name = "wow-product-edit"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# [[d1_databases]]
# binding = "DB"
# database_name = "wow-product-db"
# database_id = "INSERT_YOUR_DATABASE_ID_HERE"
